### ISSUE TITLE
It would be nice if ecsq could pull region from config

### ISSUE THREAD

**Issue by dudymas** [mightyguava/ecsq#6]
## Given
I can get clusters with:
```
$ecsq clusters --profile blah --region eu-west-1
```
And my current config looks like:
```
[blah]
mfa_serial = some:virtual:mfa::device/serial
role_arn = some:role:that::has/access-to-ecs
```

## What I did
I added 'region = eu-west-1' to the file like so:
```
[blah]
mfa_serial = some:virtual:mfa::device/serial
role_arn = some:role:that::has/access-to-ecs
region = eu-west-1
```
into my `$HOME/.aws/config` file

## Expected:
ecsq would pick up the region when I just call:
```
$ ecsq cluster --profile blah
```

## What I got:
Didn't get any results

## Thoughts:
ecsq is totally usable, but I wish I didn't have to keep track of cross region stuff. So this is more of a feature request.

**Comment by mightyguava** [comment]
I don't use roles personally, so don't know much about this. But it might have to do with that ecsq has a hard-coded default region of us-west-2 that's overriding your role config.

Could you try 5f92cac and see if that solves your problems?
